enabled: true
status: enabled
title: Vanilla
description: Stackbit Vanilla theme
supportedData: [medium]
weight: 5
author: Stackbit
authorURL: https://www.stackbit.com
images:
  small: images/demo-256x192.png
  large: images/demo-1024x768.png
