title: Hyperspace
baseurl: /
permalink: '/posts/:slug:output_ext'
footer:
  landing_style: style1-alt
  alt_style: alt
  copyright: '&copy; Hyperspace. All rights reserved.'
palette: blue
palettes:
  blue:
    sass:
      bg: '#253149'
      accent1: '#4167a6'
      accent2: '#3f8eb3'
      accent3: '#4ca07e'
  green:
    sass:
      bg: '#20313d'
      accent1: '#2e9692'
      accent2: '#3aa4ca'
      accent3: '#b84d50'
  purple:
    sass:
      bg: '#312450'
      accent1: '#5e42a6'
      accent2: '#5052b5'
      accent3: '#b74e91'
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
